AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Finovance-banking-functions

Parameters:
  stage:
    Type: String
    Description: Stage of environment (dev, stage or prod)

Conditions:
  isDev: !Equals [!Ref stage, dev]

Resources:
  # S3
  SamBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${stage}-finovance-banking-functions-stack'
