AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pet-poison-backend-functions

Resources:
  CoreBankingTpRegisterAccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'dev-banking-treasury-prime-accounts'
      AttributeDefinitions:
        - AttributeName: 'organization_id'
          AttributeType: 'S'
        - AttributeName: 'person_application_id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'organization_id'
          KeyType: HASH
        - AttributeName: 'person_application_id'
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiDefaultEndpoint:
    Description: 'API Gateway default URL'
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${stage}/'
