AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pet-poison-backend-functions

Parameters:
  stage:
    Type: String
    Description: Stage of environment (dev, stage or prod)

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${stage}-PetPoisonUserPool'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true

  AppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub '${stage}-PetPoisonRegistrationAppClient'
      GenerateSecret: false # Set this to false to create an app client with no secret
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH
      # EmailVerificationSubject: "Verify your email for our app"
      # EmailVerificationMessage: "Thanks for signing up with our app! Your verification code is {####}."
      # AdminCreateUserConfig:
      #   AllowAdminCreateUserOnly: false
      #   InviteMessageTemplate:
      #     EmailMessage: "Hello {username},\n\nYou have been invited to join our app. Click the link below to create an account:\n\n{####}\n\nThanks,\nThe Team"
      #     EmailSubject: "Invitation to join our app"

  # CoreBankingTpRegisterAccountsTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: !Sub '${stage}-banking-treasury-prime-accounts'
  #     AttributeDefinitions:
  #       - AttributeName: 'organization_id'
  #         AttributeType: 'S'
  #       - AttributeName: 'person_application_id'
  #         AttributeType: 'S'
  #     KeySchema:
  #       - AttributeName: 'organization_id'
  #         KeyType: HASH
  #       - AttributeName: 'person_application_id'
  #         KeyType: RANGE
  #     BillingMode: PAY_PER_REQUEST
# Outputs:
#   ApiDefaultEndpoint:
#     Description: 'API Gateway default URL'
#     Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${stage}/'
