name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build React application
        run: npm run build

      - name: Build SAM Application
        run: |
          sam build --use-container

      - name: Deploy SAM Application
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name pet-poison --s3-bucket amplify-cli-managed-hjddhdbsdhe \
            --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides stage=dev
